module.exports = {
  "0": "0",
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
  "6": "6",
  "7": "7",
  "8": "8",
  "9": "9",
  "kp_5": "5",
  "kp_end": "1 / End",
  "kp_downarrow": "2 / Down Arrow",
  "kp_pgdn": "3 / Page Down",
  "kp_leftarrow": "4 / Left Arrow",
  "kp_rightarrow": "6 / Right Arrow",
  "kp_home": "7 / Home",
  "kp_uparrow": "8 / Up Arrow",
  "kp_pgup": "9 / Page Up",
  "kp_ins": "0 / Insert",
  "kp_del": ". / Delete",
  "kp_slash": "/",
  "kp_multiply": "*",
  "kp_minus": "-",
  "kp_plus": "+",
  "ins": "Insert",
  "del": "Delete",
  "home": "Home",
  "end": "End",
  "pgup": "Page Up",
  "pgdn": "Page Down",
  "uparrow": "Up Arrow",
  "leftarrow": "Left Arrow",
  "downarrow": "Down Arrow",
  "rightarrow": "Right Arrow",
  "f1": "F1",
  "f2": "F2",
  "f3": "F3",
  "f4": "F4",
  "f5": "F5",
  "f6": "F6",
  "f7": "F7",
  "f8": "F8",
  "f9": "F9",
  "f10": "F10",
  "f11": "F11",
  "f12": "F12",
  "a": "A",
  "b": "B",
  "c": "C",
  "d": "D",
  "e": "E",
  "f": "F",
  "g": "G",
  "h": "H",
  "i": "I",
  "j": "J",
  "k": "K",
  "l": "L",
  "m": "M",
  "n": "N",
  "o": "O",
  "p": "P",
  "q": "Q",
  "r": "R",
  "s": "S",
  "t": "T",
  "u": "U",
  "v": "V",
  "w": "W",
  "x": "X",
  "y": "Y",
  "z": "Z",
  "enter": "Enter",
  "space": "Space Bar",
  "[": "[",
  "]": "]",
  "\\": "\\",
  ";": ";",
  "'": "'",
  ",": ",",
  ".": ".",
  "/": "/",
  "backspace": "Backspace",
  "tab": "Tab",
  "capslock": "Caps Lock",
  "shift": "Shift Left",
  "rshift": "Shift Right",
  "ctrl": "Control Left",
  "rctrl": "Control Right",
  "alt": "Alt Left",
  "ralt": "Alt Right",
  "mouse1": "Left Mouse",
  "mouse2": "Right Mouse",
  "mouse3": "Middle Mouse",
  "mouse4": "Side Mouse 1",
  "mouse5": "Side Mouse 2",
  "mwheeldown": "Mouse Wheel Down",
  "mwheelup": "Mouse Wheel Up"
}
